from typing import TypedDict, List, Annotated
import operator

# The State defines the "memory" of our Multi-Agent system.
# Every agent will read from this, do its job, and append its results.
class CopilotState(TypedDict):
    # The original instruction given by user (e.g., "Build a website from my downloads")
    user_prompt: str 
    
    # Information retrieved from the web by the Gemini agent
    web_research_summary: str 
    
    # Paths to files found by the OS agent
    local_file_paths: Annotated[List[str], operator.add]
    
    # The final HTML/React code generated by the GPT-4o agent
    generated_code: str
    
    # To track what step we are currently on
    current_status: str